<td><input type="text" id="thread_title" name="thread_title" value="" size="20" /></td>
<td align="center">Name<br>time()</td>
<td align="center">0</td>
<td><input type="button" id="f_create_submit" name="f_create_submit" onClick="javascript:submitForm('create','<?php echo $this->url( array( 'controller'=>'thread', 'action'=>'create', 'format'=>'json' ) ); ?>','JSON',null);" value="Erstellen!" /></td>