<?php $this->headLink()->appendStylesheet( $this->baseUrl().'/css/menu.css' ); ?>
<div id="win_menu" class="win" style="top: 75px; left: 75px;"> 
	<div id="win_menu_top" class="topbar">Hauptmen&uuml;</div> 
	<div id="win_menu_res" class="resizer"></div>
	<?php echo $this->loggedInUser(); ?>
	<ul id="main-menu">
		<?php echo $this->partialLoop( 'index/_menuItem.phtml', $this->menu ); ?>
	</ul>
</div>